[workspace]
resolver = "3"
members = [ "jni/hello-world/mylib","pkg/*"]
exclude = ["pkg/call-rust-from-c-static", "pkg/call-rust-from-c-dynamic"]

[workspace.dependencies]
cc = "1.2.30"
eyre = "0.6.12"
jni = "0.21.1"
